replicaCount: 1

image:
  repository: piyushroshan/auth0app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  # Supported types: ClusterIP, LoadBalancer
  type: ClusterIP
  port: 5000
  # Set to true to also create a LoadBalancer service
  createLoadBalancer: false
  loadBalancerPort: 5555

env:
  AUTH0_DOMAIN: "your-domain.auth0.com"
  AUTH0_CLIENT_ID: "your-client-id"
  AUTH0_CLIENT_SECRET: "your-client-secret"
  SECRET_KEY: "your-secret-key"
  AUTH0_CALLBACK_URL: "http://example.com"

resources: {}

