apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "auth0-flask-app.fullname" . }}
  labels:
    app: {{ include "auth0-flask-app.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "your-app.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "auth0-flask-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
